name: build pull request

on:
   pull_request:
     types:
       - opened
       - reopened
       - edited
   workflow_dispatch:    

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-java@v5
              with:
                  distribution: 'temurin'
                  java-version: '21'
                  cache: 'gradle'
            - name: Run tests
              run: |
                ./gradlew test
            - name: Run clean build
              run: |
                ./gradlew clean build -x test
